/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package gloss-1.13.2.2 */
#ifndef VERSION_gloss
#define VERSION_gloss "1.13.2.2"
#endif /* VERSION_gloss */
#ifndef MIN_VERSION_gloss
#define MIN_VERSION_gloss(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  13 || \
  (major1) == 1 && (major2) == 13 && (minor) <= 2)
#endif /* MIN_VERSION_gloss */
/* package GLUT-2.7.0.16 */
#ifndef VERSION_GLUT
#define VERSION_GLUT "2.7.0.16"
#endif /* VERSION_GLUT */
#ifndef MIN_VERSION_GLUT
#define MIN_VERSION_GLUT(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  7 || \
  (major1) == 2 && (major2) == 7 && (minor) <= 0)
#endif /* MIN_VERSION_GLUT */
/* package OpenGL-3.0.3.0 */
#ifndef VERSION_OpenGL
#define VERSION_OpenGL "3.0.3.0"
#endif /* VERSION_OpenGL */
#ifndef MIN_VERSION_OpenGL
#define MIN_VERSION_OpenGL(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  0 || \
  (major1) == 3 && (major2) == 0 && (minor) <= 3)
#endif /* MIN_VERSION_OpenGL */
/* package base-4.18.2.1 */
#ifndef VERSION_base
#define VERSION_base "4.18.2.1"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  18 || \
  (major1) == 4 && (major2) == 18 && (minor) <= 2)
#endif /* MIN_VERSION_base */
/* package bmp-1.2.6.4 */
#ifndef VERSION_bmp
#define VERSION_bmp "1.2.6.4"
#endif /* VERSION_bmp */
#ifndef MIN_VERSION_bmp
#define MIN_VERSION_bmp(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 6)
#endif /* MIN_VERSION_bmp */
/* package bytestring-0.11.5.3 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.11.5.3"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  11 || \
  (major1) == 0 && (major2) == 11 && (minor) <= 5)
#endif /* MIN_VERSION_bytestring */
/* package containers-0.6.7 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.7"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 7)
#endif /* MIN_VERSION_containers */
/* package ghc-prim-0.10.0 */
#ifndef VERSION_ghc_prim
#define VERSION_ghc_prim "0.10.0"
#endif /* VERSION_ghc_prim */
#ifndef MIN_VERSION_ghc_prim
#define MIN_VERSION_ghc_prim(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 0)
#endif /* MIN_VERSION_ghc_prim */
/* package gloss-rendering-1.13.1.2 */
#ifndef VERSION_gloss_rendering
#define VERSION_gloss_rendering "1.13.1.2"
#endif /* VERSION_gloss_rendering */
#ifndef MIN_VERSION_gloss_rendering
#define MIN_VERSION_gloss_rendering(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  13 || \
  (major1) == 1 && (major2) == 13 && (minor) <= 1)
#endif /* MIN_VERSION_gloss_rendering */

/* tool gcc-14.0.6 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "14.0.6"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  14 || \
  (major1) == 14 && (major2) <  0 || \
  (major1) == 14 && (major2) == 0 && (minor) <= 6)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.6.5 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.6.5"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  6 || \
  (major1) == 9 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.6.5 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.6.5"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  6 || \
  (major1) == 9 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.29.2 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.29.2"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  29 || \
  (major1) == 2 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool hpc-0.68 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.68"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.9 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.9"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 9)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool pkg-config-2.2.0 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "2.2.0"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_pkg_config */
/* tool runghc-9.6.5 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.6.5"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  6 || \
  (major1) == 9 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "gloss-1.13.2.2-16ZNb7pkabm3INkWzKjwmL"
#endif /* CURRENT_packageKey */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "gloss-1.13.2.2-16ZNb7pkabm3INkWzKjwmL"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "1.13.2.2"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
